Fix compile on sytems using libc++ instead of libstdc++
libc++ does not really implement __gnu_cxx namespace and it
compiles fine without this namespace, therefore detect libc++
and if it is used them exclude this namespace

See https://github.com/stressapptest/stressapptest/issues/47

Fixes

./sattypes.h:33:17: error: expected namespace name
using namespace __gnu_cxx; //NOLINT

Signed-off-by: Khem Raj <raj.khem@gmail.com>